exporter_name: products_csv
exporter_type: json
collection: products
fields:
 - header: "gid"
   path: "_gid"
 - header: "created_at"
   path: "_created_at"
 - header: "title"
   path: "title"
 - header: "price"
   path: "price"
 - header: "feedback"
   path: "feedback"
 - header: "seller"
   path: "seller"